### ISSUE TITLE
No such file or directory: 'data_files/<>_haplotype_timecourse.txt'

### ISSUE THREAD

**Issue by rraadd88** [benjaminhgood/LTEE-metagenomic#1]
Hi, I was trying to make the timecourse figure using following command:

`$ python plot_timecourse.py argR.settings.txt`

But seems like some file named 'haplotype_timecourse.txt' is missing in data_files folder.
``` 
Processing Ara-5...
Traceback (most recent call last):
  File "plot_timecourse.py", line 84, in <module>
    dummy_times,fmajors,fminors,haplotype_trajectories = parse_file.parse_haplotype_timecourse(population)
  File "/path/to/LTEE-metagenomic/parse_file.py", line 1005, in parse_haplotype_timecourse
    file = open(haplotype_filename,"r")
IOError: [Errno 2] No such file or directory: 'data_files/m5_haplotype_timecourse.txt'
```
Please let me know if I need to generate it using some other script or something.
Thanks.

**Comment by benjaminhgood** [comment]
Yes, sorry for the poor documentation. These files should be generated by running the script

`$ python process_cluster_output.py`

(I've also added these instructions to the README.md file.)

**Comment by rraadd88** [comment]
It kinda worked. There was a silent error at the start: `IOError: [Errno 2] No such file or directory: 'cluster_output_files/m5_likelihood_timecourse.txt'`. Thereon it seemed to run fine.
```
$ python process_cluster_output.py


Trajectory post-processing output for LTEE metagenomic sequencing project
Date: 2017-11-16

Performing final filtering and annotation step...
Filtering trajectories with FDR=0.05
Traceback (most recent call last):
  File "combined_annotate_timecourse.py", line 28, in <module>
    file = open(input_filename_template % population,"r") 
IOError: [Errno 2] No such file or directory: 'cluster_output_files/m5_likelihood_timecourse.txt'
Error!
Inferring trajectory states in well-mixed HMM...
Processing m5
Processing p2
Processing p4
Processing p1
Processing m6
Processing p5
Processing m1
Processing m2
Processing m3
Processing m4
Processing p3
Processing p6
Done!
..
..
```
Thanks for the prompt response.

**Comment by Yixiangzhang1996** [comment]
really mess scripts......
